ada-url/rust

Cargo.lock
Cargo.toml
src/lib.rs

Fixes https://github.com/ada-url/rust/issues/19

feat: add serde serialize/deserialize support

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
build.rs
deps/wasi_to_unknown.cpp

This adds ability to compile for wasm32-wasi and wasm32-unknown-unknown targets.
Both of those use WASI SDK for compilation and add necessary flags for linking C++ library. wasm32-wasi is a bit more straightforward, while wasm32-unknown-unknown requires a few hacks to get a pure Wasm output w/o any imports, but at least it can work too. [Demo](https://github.com/RReverser/ada-wbg):
While changing flags in build.rs, also leveraged some new `cc` options and made it possible to compile on Windows via Clang instead of MSVC if user chooses to do so.

Make ada-rust compile for wasm32-wasi and -unknown

---

src/lib.rs

@anonrig Is there any reason `origin` must take mutable `self`? If not, this can be merged. If there is a reason, feel free to close this PR.

feat: remove `mut`

---

deps/ada.cpp
deps/ada.h
deps/ada_c.h
src/ffi.rs
src/lib.rs

Thanks to @steveklabnik, Ada rust crate can have safe & correct cloning.
Co-authored-by: Steve Klabnik

fix: properly `clone` url

---

src/lib.rs

Fixes https://github.com/ada-url/rust/issues/29

doc: add comments for setter functions

---

src/lib.rs

It's more concise and idiomatic to use `then_some`.

Simplify from ada_url_components.

---

src/lib.rs

Normally, the `Err` variant should contain more information than `()` (such as an error message, for instance), but since I don't know what are the edge cases, I don't know how to write the error message.
This change is a breaking change.

feat: fallible setters should return result

---

Cargo.lock
Cargo.toml
src/lib.rs

* `thiserror` has been replaced with `derive_more`:
- `thiserror` cannot handle generic bounds.
* The `Error` type has been replaced with `ParseUrlError`:
- It only has one variant anyway.
* This is a breaking change.

feat: error type without allocation

---

README.md

* Unnecessary because users should already know the basics of their language.
* Incorrect because:
- The feature named `derive` doesn't exist.
- The version is `1`, but the next release is going to be a breaking change (https://github.com/ada-url/rust/pull/36, https://github.com/ada-url/rust/pull/37).
* Keeping these lines also complicate the process of publishing breaking changes, so it is better to remove it completely.

docs: remove an unnecessary and incorrect guide

---

.github/workflows/ci.yml

Shows that https://github.com/ada-url/rust/issues/43 is invalid. The reporter probably attempts to use libc++ on a system that does not support libc++. There is nothing that this crate can do if you require it to use libc++ but libc++ is not available. It must fail.

Adding libcpp tests

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md
bench/parse.rs
src/lib.rs
test.sh

closes https://github.com/ada-url/rust/pull/41

feat: no-std

---

deps/ada.cpp
deps/ada.h
deps/ada_c.h

This PR updates ada to v2.6.7 which mainly fixes a typo and renames `ada_get_schema_type` to `ada_get_scheme_type`.

chore: update ada to v2.6.7

---

src/ffi.rs
src/lib.rs

This PR addresses #51 and adds a new getter to retrieve the schema type.

feat: add getter for scheme type

---

README.md
examples/simple.rs
src/ffi.rs
src/idna.rs
src/lib.rs

- **docs: Fix sample code**
- **docs: Use unused `Result`**
- **feat!: `Error` for `SetterResult`**
- **chore: Fix various `clippy` lints**
- **docs: Dedicated `examples/`**
- **docs: Apply Markdown lints**

Improve error handling ergonomics (and docs around it)

---

src/ffi.rs

While working on #63, I noticed that my Drop wasn't correctly working because the Rust Implementation was assuming that the C parameters are passed by pointer, while they are actually passed by value
Then on a deeper check of the C code, found it at https://github.com/ada-url/ada/blob/1227f60798b05a04412af867d2f13ed20ead9243/include/ada_c.h#L53C6-L53C27.
BREAKING CHANGE: ada_free_owned_string parameter pass by value not pointer. Closes #64

fix(ffi/ada_free_owned_string): c parameter is passed by value

---

justfile

Allows for formatting of source code when running just all
Using the [fmt naming from Just's own](https://github.com/casey/just/blob/d15dad66c9d1cd342b99d0de2d2e99a610ee2fd8/justfile#L39)
This would ideally reduce silly mistakes on commits such as my own in #65.

build(justfile): add format support

---

src/ffi.rs
src/idna.rs
src/lib.rs

1. The previous approach would leak memory
1. Returns an owned string
2. No memory leaks
1. ada_owned_string now implements Drop trait.   
This would lead to the freeing of memory upon its going out of scope breaking existing code.   
This behaviour is probably more Rust-like but breaks user-space.  
The alternative is to not impement Drop and it could be done.  
However, this would make it user space's responsibility and hence not exactly an ideal behaviour
2. Usage of as_ref needed to convert to &str as can be seen in unit tests.  
This can be resolved by probably implementing conversion functions if needed for Display, to_string etc. in std mode for end-user ease.
1. Returning String  
Would lead to a major breaking change.  
The approach would lead to all 3 functions no longer working …

In functions using ada_owned_string, return ada_owned_string instead of &str

---

Cargo.lock
Cargo.toml

Let's release v3.0.0. This is a breaking change because of how `to_ascii` and `to_unicode` return values are changed.

chore: release v3.0.0

---

README.md
bench/parse.rs
rust-toolchain.toml
src/ffi.rs

- **feat: add can_parse to benchmarks**
- **chore: update rust to v1.79.0**

Update benchmarks and Rust

---

src/ffi.rs
src/lib.rs
src/url_search_params.rs

Some traits are missing. Since I'm not using Rust daily, I don't know which traits are beneficial to be implemented into the new structs. 
Please review and give recommendations around the missing structs and the API surface.

Add url search params

---

.github/workflows/release.yml

Adds a release workflow that can be manually triggered via workflow dispatch.
- First runs a test stage similar to `ci.yml` that:
- Tests across multiple platforms (Windows, Ubuntu, MacOS)
- Includes WASM testing
- Runs cargo-semver-check on Ubuntu runs
- If tests pass, runs a publish stage that:
- Publishes to crates.io
- Creates git tags
- Creates GitHub releases
- `CARGO_REGISTRY_TOKEN` secret must be configured in repository settings
Closes #72
> A future improvement could be to use a reusable workflow for the test-release workflow.

ci: add github release workflow
